#!/bin/bash

# Get script directory
SCRIPT_DIR=$(dirname $0)

# OpenStack credentials
if [ "$1" != "--no_source" ]; then
  source ${SCRIPT_DIR}/openrc.sh
fi

# Remove IP files
rm -f ${SCRIPT_DIR}/BuilderIP

# Delete master image server if exists
if [ $(openstack server list | grep "\<BuilderMaster\>" | wc -l) == 1 ]; then
    openstack server delete --wait BuilderMaster
fi

# Delete master image if it exists
if [ $(openstack image list | grep "\<Builder\>" | wc -l) == 1 ]; then
    openstack image delete --wait "BuilderImage"
fi

#TODO I don't think this will work if multiple builders are spunup - need to use UUID

# Delete any builders that exist
if [ $(openstack server list | grep "\<Builder\>" | wc -l) > 0 ]; then
    openstack server delete Builder
fi