#!/usr/bin/env bash

set -e
set -o xtrace

# Create non root builder user
useradd --create-home --home-dir /home/builder --shell /bin/bash builder

# Allow builder to run singularity as root
echo 'builder ALL=(ALL) NOPASSWD: /usr/local/bin/singularity' > /etc/sudoers.d/builder
echo 'builder ALL=(ALL) NOPASSWD: /usr/bin/unbuffer' >> /etc/sudoers.d/builder
chmod 0440 /etc/sudoers.d/builder

apt-get -y update
apt-get -y install expect

# Install Singularity
export VERSION=2.4
wget https://github.com/singularityware/singularity/releases/download/${VERSION}/singularity-${VERSION}.tar.gz
tar xvf singularity-${VERSION}.tar.gz
cd singularity-${VERSION}
./configure --prefix=/usr/local
make
make install

# Update cmake version
cd /
wget https://cmake.org/files/v3.9/cmake-3.9.5-Linux-x86_64.sh
chmod +x ./cmake-3.9.5-Linux-x86_64.sh
./cmake-3.9.5-Linux-x86_64.sh --skip-license
ln -s /cmake-3.9.5-Linux-x86_64/bin/* /usr/local/bin
cd /
rm -rf /cmake-3.9.5-Linux-x86_64

# Install a new version of boost
cd /
wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz
tar xf boost_1_65_1.tar.gz
cd boost_1_65_1
./bootstrap.sh --with-libraries=filesystem,regex,system,coroutine,serialization,log,thread
./b2 install || :
rm -rf /boost_1_65_1

# Install ContainerBuilder
cd /
git clone https://github.com/AdamSimpson/ContainerBuilder.git
cd ContainerBuilder
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr/local" ..
make
make install
rm -rf /ContainerBuilder

# Create systemd script and launch the Builder daemon
cat << EOF > /etc/systemd/system/ContainerBuilder.service
[Unit]
Description=ContainerBuilder daemon
After=network.target

[Service]
Type=simple
User=builder
WorkingDirectory=/home/builder
Environment="LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib"
ExecStart=/usr/local/bin/ContainerBuilder
Restart=no

[Install]
WantedBy=multi-user.target
EOF
systemctl enable ContainerBuilder

# Disable TCP time stamps - ORNL seems to be jacking them up and causing the connection to drop at the 5 minute mark
at << EOF > /etc/sysctl.d/51-net.conf
net.ipv4.tcp_timestamps = 0
EOF

reboot

# To check that the Builder service is running
# sudo netstat -plnt | grep ContainerBuilder
# systemctl status
