#!/bin/bash

# If a failure is encountered return immediately
set -e

# OpenStack credentials
source /home/queue/openrc.sh

# General VM settings
BOOTIMG="BuilderImage"
ZONE="nova"
FLAVOR="m1.medium"
KEY="ContainerBuilderKey"

NIC=$(openstack network show -c id --format value or_provider_general_extnetwork1)

# Startup new VM
ID=$(openstack server create       \
    --image "${BOOTIMG}"          \
    --flavor "${FLAVOR}"          \
    --availability-zone "${ZONE}" \
    --nic net-id="${NIC}"         \
    --key-name "${KEY}"           \
    --wait                        \
    -c id                         \
    -f value                      \
    "Builder")

# If the build doesn't return a failure code echo the ID, IP address, and port of the builder service
IP=$(openstack server show -c addresses -f value ${ID} | sed -e "s/^or_provider_general_extnetwork1=//")
PORT="8080"
echo ${ID}
echo ${IP}
echo ${PORT}