#!/bin/bash

# Get script directory
SCRIPT_DIR=$(dirname $0)

# OpenStack credentials
if [ "$1" != "--no_source" ]; then
  source ${SCRIPT_DIR}/openrc.sh
fi

# Remove Keys
nova keypair-delete ResourceQueueKey
rm ${SCRIPT_DIR}/ResourceQueueKey

# Remove IP files
rm ${SCRIPT_DIR}/ResourceQueueIP

# Delete VM
nova delete ResourceQueue
