#!/bin/bash

# Get script directory
SCRIPT_DIR=$(dirname $0)

# OpenStack credentials
if [ "$1" != "--no_source" ]; then
  source ${SCRIPT_DIR}/openrc.sh
fi

# Remove Keys
openstack keypair delete ContainerBuilderKey
rm ${SCRIPT_DIR}/ContainerBuilderKey

# Remove IP files
rm ${SCRIPT_DIR}/ResourceQueueIP

# Delete VM
openstack server delete ResourceQueue
