#!/bin/bash

# Get script directory
SCRIPT_DIR=$(dirname $0)

# OpenStack credentials
if [ "$1" != "--no_source" ]; then
    source ${SCRIPT_DIR}/openrc.sh
fi

# Remove Keys
if [ $(openstack keypair list | grep ContainerBuilderKey | wc -l) == 1 ]; then
    openstack keypair delete ContainerBuilderKey
    rm ${SCRIPT_DIR}/ContainerBuilderKey
fi

# Remove IP files
rm -f ${SCRIPT_DIR}/ResourceQueueIP

# Delete VM
if [ $(openstack server list | grep ResourceQueue | wc -l) == 1 ]; then
    openstack server delete ResourceQueue
fi
